import { Injectable } from '@angular/core';

@Injectable({
    providedIn: 'root'
})
export class Icons {
    public icons = {
        1: {
          1: { 'icon': 'assets/images/coche_verde.png' },
          2: { 'icon': 'assets/images/coche_gris.png' },
          3: { 'icon': 'assets/images/coche_amarillo.png' },
          4: { 'icon': 'assets/images/coche_naranja.png' },
          5: { 'icon': 'assets/images/coche_azul.png' },
          6: { 'icon': 'assets/images/coche_rojo.png' },
          7: { 'icon': 'assets/images/coche_rojo.png'},
          10: { 'icon': 'assets/images/coche_rojo.png'},
        },
        2: {
          1: { 'icon': 'assets/images/coche_verde.png' },
          2: { 'icon': 'assets/images/coche_gris.png' },
          3: { 'icon': 'assets/images/coche_amarillo.png' },
          4: { 'icon': 'assets/images/coche_naranja.png' },
          5: { 'icon': 'assets/images/coche_azul.png' },
          6: { 'icon': 'assets/images/coche_rojo.png' },
          7: { 'icon': 'assets/images/coche_rojo.png'},
          10: { 'icon': 'assets/images/coche_rojo.png'},
        },
        3: {
          1: { 'icon': 'assets/images/coche_verde.png' },
          2: { 'icon': 'assets/images/coche_gris.png' },
          3: { 'icon': 'assets/images/coche_amarillo.png' },
          4: { 'icon': 'assets/images/coche_naranja.png' },
          5: { 'icon': 'assets/images/coche_azul.png' },
          6: { 'icon': 'assets/images/coche_rojo.png' },
          7: { 'icon': 'assets/images/coche_rojo.png'},
          10: { 'icon': 'assets/images/coche_rojo.png'}
        },
        4: {
          1: { 'icon': 'assets/images/camion_verde.png' },
          2: { 'icon': 'assets/images/camion_gris.png' },
          3: { 'icon': 'assets/images/camion_amarillo.png' },
          4: { 'icon': 'assets/images/camion_naranja.png' },
          5: { 'icon': 'assets/images/camion_azul.png' },
          6: { 'icon': 'assets/images/camion_rojo.png' },
          7: { 'icon': 'assets/images/camion_rojo.png'},
          10: { 'icon': 'assets/images/camion_rojo.png'},
        },
        5: {
          1: { 'icon': 'assets/images/moto_verde.png' },
          2: { 'icon': 'assets/images/moto_gris.png' },
          3: { 'icon': 'assets/images/moto_amarillo.png' },
          4: { 'icon': 'assets/images/moto_naranja.png' },
          5: { 'icon': 'assets/images/moto_azul.png' },
          6: { 'icon': 'assets/images/moto_rojo.png' },
          7: { 'icon': 'assets/images/moto_rojo.png'},
          10: { 'icon': 'assets/images/moto_rojo.png'},
        },
        6: {
          1: { 'icon': 'assets/images/celular_verde.png' },
          2: { 'icon': 'assets/images/celular_gris.png' },
          3: { 'icon': 'assets/images/celular_amarillo.png' },
          4: { 'icon': 'assets/images/celular_naranja.png' },
          5: { 'icon': 'assets/images/celular_azul.png' },
          6: { 'icon': 'assets/images/celular_rojo.png' },
          7: { 'icon': 'assets/images/celular_rojo.png'},
          10: { 'icon': 'assets/images/coche_rojo.png'},
        },
        7: {
          1: { 'icon': 'assets/images/moto_verde.png' },
          2: { 'icon': 'assets/images/moto_gris.png' },
          3: { 'icon': 'assets/images/moto_amarillo.png' },
          4: { 'icon': 'assets/images/moto_naranja.png' },
          5: { 'icon': 'assets/images/moto_azul.png' },
          6: { 'icon': 'assets/images/moto_rojo.png' },
          7: { 'icon': 'assets/images/moto_rojo.png'},
          10: { 'icon': 'assets/images/moto_rojo.png'},
        },
        8: {
          1: { 'icon': 'assets/images/coche_verde.png' },
          2: { 'icon': 'assets/images/coche_gris.png' },
          3: { 'icon': 'assets/images/coche_amarillo.png' },
          4: { 'icon': 'assets/images/coche_naranja.png' },
          5: { 'icon': 'assets/images/coche_azul.png' },
          6: { 'icon': 'assets/images/coche_rojo.png' },
          7: { 'icon': 'assets/images/coche_rojo.png'},
          10: { 'icon': 'assets/images/coche_rojo.png'},
        }
    };

    public iconosFrente = {
        0: {
          1: { 'icon': 'assets/images/cocheFrente_verde.png' },
          2: { 'icon': 'assets/images/cocheFrente_gris.png' },
          3: { 'icon': 'assets/images/cocheFrente_amarillo.png' },
          4: { 'icon': 'assets/images/cocheFrente_naranja.png' },
          5: { 'icon': 'assets/images/cocheFrente_azul.png' },
          6: { 'icon': 'assets/images/cocheFrente_rojo.png' },
          7: { 'icon': 'assets/images/cocheFrente_rojo.png'},
          10: { 'icon': 'assets/images/cocheFrente_rojo.png'},
        },
        1: {
          1: { 'icon': 'assets/images/cocheFrente_verde.png' },
          2: { 'icon': 'assets/images/cocheFrente_gris.png' },
          3: { 'icon': 'assets/images/cocheFrente_amarillo.png' },
          4: { 'icon': 'assets/images/cocheFrente_naranja.png' },
          5: { 'icon': 'assets/images/cocheFrente_azul.png' },
          6: { 'icon': 'assets/images/cocheFrente_rojo.png' },
          7: { 'icon': 'assets/images/cocheFrente_rojo.png'},
          10: { 'icon': 'assets/images/cocheFrente_rojo.png'},
        },
        2: {
            1: { 'icon': 'assets/images/cocheFrente_verde.png' },
            2: { 'icon': 'assets/images/cocheFrente_gris.png' },
            3: { 'icon': 'assets/images/cocheFrente_amarillo.png' },
            4: { 'icon': 'assets/images/cocheFrente_naranja.png' },
            5: { 'icon': 'assets/images/cocheFrente_azul.png' },
            6: { 'icon': 'assets/images/cocheFrente_rojo.png' },
            7: { 'icon': 'assets/images/cocheFrente_rojo.png'},
            10: { 'icon': 'assets/images/cocheFrente_rojo.png'},
        },
        3: {
            1: { 'icon': 'assets/images/cocheFrente_verde.png' },
            2: { 'icon': 'assets/images/cocheFrente_gris.png' },
            3: { 'icon': 'assets/images/cocheFrente_amarillo.png' },
            4: { 'icon': 'assets/images/cocheFrente_naranja.png' },
            5: { 'icon': 'assets/images/cocheFrente_azul.png' },
            6: { 'icon': 'assets/images/cocheFrente_rojo.png' },
            7: { 'icon': 'assets/images/cocheFrente_rojo.png'},
            10: { 'icon': 'assets/images/cocheFrente_rojo.png'},
        },
        4: {
          1: { 'icon': 'assets/images/camionFrente_verde.png' },
          2: { 'icon': 'assets/images/camionFrente_gris.png' },
          3: { 'icon': 'assets/images/camionFrente_amarillo.png' },
          4: { 'icon': 'assets/images/camionFrente_naranja.png' },
          5: { 'icon': 'assets/images/camionFrente_azul.png' },
          6: { 'icon': 'assets/images/camionFrente_rojo.png' },
          7: { 'icon': 'assets/images/camionFrente_rojo.png'},
          10: { 'icon': 'assets/images/camionFrente_rojo.png'},
        },
        5: {
          1: { 'icon': 'assets/images/motoFrente_verde.png' },
          2: { 'icon': 'assets/images/motoFrente_gris.png' },
          3: { 'icon': 'assets/images/motoFrente_amarillo.png' },
          4: { 'icon': 'assets/images/motoFrente_naranja.png' },
          5: { 'icon': 'assets/images/motoFrente_azul.png' },
          6: { 'icon': 'assets/images/motoFrente_rojo.png' },
          7: { 'icon': 'assets/images/motoFrente_rojo.png'},
          10: { 'icon': 'assets/images/motoFrente_rojo.png'}
        },
        6: {
            1: { 'icon': 'assets/images/celular_verde.png' },
            2: { 'icon': 'assets/images/celular_gris.png' },
            3: { 'icon': 'assets/images/celular_amarillo.png' },
            4: { 'icon': 'assets/images/celular_naranja.png' },
            5: { 'icon': 'assets/images/celular_azul.png' },
            6: { 'icon': 'assets/images/celular_rojo.png' },
            7: { 'icon': 'assets/images/celular_rojo.png'},
            10: { 'icon': 'assets/images/celular_rojo.png'},
        } ,
        7: {
          1: { 'icon': 'assets/images/moto_verde.png' },
          2: { 'icon': 'assets/images/moto_gris.png' },
          3: { 'icon': 'assets/images/moto_amarillo.png' },
          4: { 'icon': 'assets/images/moto_naranja.png' },
          5: { 'icon': 'assets/images/moto_azul.png' },
          6: { 'icon': 'assets/images/moto_rojo.png' },
          7: { 'icon': 'assets/images/moto_rojo.png'},
          10: { 'icon': 'assets/images/moto_rojo.png'},
        },
        8: {
            1: { 'icon': 'assets/images/cocheFrente_verde.png' },
            2: { 'icon': 'assets/images/cocheFrente_gris.png' },
            3: { 'icon': 'assets/images/cocheFrente_amarillo.png' },
            4: { 'icon': 'assets/images/cocheFrente_naranja.png' },
            5: { 'icon': 'assets/images/cocheFrente_azul.png' },
            6: { 'icon': 'assets/images/cocheFrente_rojo.png' },
            7: { 'icon': 'assets/images/cocheFrente_rojo.png'},
            10: { 'icon': 'assets/images/cocheFrente_rojo.png'},
        }
    };

}
